# Generated by Django 5.0.1 on 2024-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0003_rename_employee_detail_employeedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
