# Generated by Django 5.0.1 on 2024-03-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0005_remove_employeedetail_id_alter_employeedetail_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='country',
        ),
    ]
