# Generated by Django 5.0.1 on 2024-03-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0007_employeeeducation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1_name', models.CharField(max_length=200, null=True)),
                ('company1_designation', models.CharField(max_length=200, null=True)),
                ('company1_salary', models.CharField(max_length=100, null=True)),
                ('company1_duration', models.CharField(max_length=100, null=True)),
                ('company2_name', models.CharField(max_length=200, null=True)),
                ('company2_designation', models.CharField(max_length=200, null=True)),
                ('company2_salary', models.CharField(max_length=100, null=True)),
                ('company2_duration', models.CharField(max_length=100, null=True)),
                ('company3_name', models.CharField(max_length=200, null=True)),
                ('company3_designation', models.CharField(max_length=200, null=True)),
                ('company3_salary', models.CharField(max_length=100, null=True)),
                ('company3_duration', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
