# Generated by Django 5.0.1 on 2024-03-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0008_employeeexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='year_of_Passing_hsc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
