# Generated by Django 5.0.1 on 2024-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0009_employeeeducation_year_of_passing_hsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='year_of_Passing_grad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
