# Generated by Django 5.0.1 on 2024-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0010_alter_employeeeducation_year_of_passing_grad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentage_grad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
